import type { Locale } from "../domain";

export const UI_COPY = {
  zh: {
    brand: "命运轴",
    eyebrow: "OC FATE LOOM · 第三版",
    title: "让选择彼此施压，直到命运显形。",
    lede: "不必填满所有轴。先选最想确认的几件事，右侧会显示它们如何共同形成抉择、代价与终局。",
    generationGoal: "这次想生成到哪里？",
    openingMode: "人物＋开场",
    openingModeDesc: "角色核心、关系手感与一个可继续写的场景",
    timelineMode: "完整命运线",
    timelineModeDesc: "从相遇写到抉择、代价与终局回收",
    help: "使用说明",
    switchLanguage: "Switch to English",
    selected: "已选",
    axes: "轴",
    fatePanel: "命运脉络",
    fatePanelDesc: "只展示已经成立的因果与关系",
    linkage: "条联动",
    emptyFate: "尚未形成联动。先选一条境遇或内核轴，这里会显示它如何牵动后续。",
    relations: "关系支线",
    causalSpine: "已成立的因果主干",
    selectedSignals: "已经进入命运线的设定",
    openKnots: "待承接的结",
    chooseAxis: "前往选择",
    showFate: "查看命运脉络",
    getStarter: "给我一个起点",
    fillGap: "帮我补足",
    reroll: "全部重抽",
    undo: "撤销重抽",
    clearAxis: "暂不设定",
    learnAxis: "了解这条轴",
    previous: "上一章",
    next: "下一章",
    extraLabel: "补充要求",
    extraHint: "可选，不写也能生成",
    extraPlaceholder: "例如：关系推进克制；不要说教或浪子回头式洗白；开场是低照度雨夜……",
    connection: "生成方式",
    defaultMode: "站点体验",
    customMode: "自带密钥",
    defaultUnavailable: "站点体验暂未开放",
    defaultUnavailableDesc: "供应商、模型与站点中转服务目前均留空，系统不会回退到旧配置。",
    localPreviewReady: "本地演示可用",
    localPreviewDesc: "本次预览使用确定性示例文本，不调用任何模型，也不会发出网络请求。",
    noProvider: "暂无已审核供应商",
    provider: "供应商",
    modelId: "模型 ID",
    apiKey: "API Key",
    clearKey: "立即清除",
    privacy: "本站只把密钥保留在当前页面内存，不写入本地存储、Cookie、日志或数据库；刷新、关闭页面或点击清除后会主动丢弃。浏览器、扩展与供应商仍可能按各自机制处理，请拒绝密码管理器保存，并使用限额、可撤销的专用 Key。",
    route: "传输路线",
    routeBrowser: "浏览器",
    routeEmpty: "尚未选择供应商",
    copyFailed: "复制失败，请使用下载功能或手动选择正文。",
    selectedSummary: "已选 {count} 条轴，其中 {structure} 条参与命运结构",
    semanticRequirement: "至少从境遇、内核、关系三个章节各选一条",
    previewResult: "预览结果",
    generate: "开始生成",
    cancel: "取消",
    resultEyebrow: "本次命运脉络",
    resultTitle: "命运已经显形",
    backToAxes: "调整轴后再生成",
    copyAll: "复制全文",
    copied: "已复制",
    download: "下载 Markdown",
    outline: "结果目录",
    sourceLocal: "本地演示 · 无网络请求",
    sourcePending: "尚未连接模型",
    incomplete: "还缺少三个叙事锚点",
    incompleteDetail: "请从境遇、内核、关系章节各选至少一条，或者让系统给你一个起点。",
    helpTitle: "怎样使用命运轴",
    helpIntro: "轴不是必须填满的问卷，而是一组可以彼此施压的叙事变量。",
    helpPointOne: "先选三个锚点：一条境遇、一条内核、一条关系。",
    helpPointTwo: "右侧命运脉络只显示已成立的规则，不会凭空解释。",
    helpPointThree: "高张力组合不会被判错；系统只会提示它需要怎样的叙事承接。",
    close: "关闭",
    paletteOutside: "文字质感不会进入命运因果线。",
  },
  en: {
    brand: "Fate Loom",
    eyebrow: "OC FATE LOOM · VERSION III",
    title: "Let every choice exert pressure until fate takes shape.",
    lede: "You do not need to fill every axis. Choose what matters first; the thread will show how those choices form a decision, a cost, and an ending.",
    generationGoal: "How far should this generation go?",
    openingMode: "Character + opening",
    openingModeDesc: "Core character, relationship texture, and a scene to continue",
    timelineMode: "Full fate line",
    timelineModeDesc: "From encounter through choice, cost, and final resolution",
    help: "How it works",
    switchLanguage: "切换到中文",
    selected: "Selected",
    axes: "axes",
    fatePanel: "Fate thread",
    fatePanelDesc: "Only established causal and relational links appear",
    linkage: "links",
    emptyFate: "No linkage yet. Choose a circumstance or core axis to see what it begins to pull.",
    relations: "Relational branches",
    causalSpine: "Established causal spine",
    selectedSignals: "Selections already on the fate line",
    openKnots: "Open knots",
    chooseAxis: "Choose axis",
    showFate: "View fate thread",
    getStarter: "Give me a starting point",
    fillGap: "Fill one gap",
    reroll: "Reroll everything",
    undo: "Undo reroll",
    clearAxis: "Leave open",
    learnAxis: "About this axis",
    previous: "Previous",
    next: "Next",
    extraLabel: "Additional direction",
    extraHint: "Optional",
    extraPlaceholder: "For example: restrained progression; no moralizing; open on a low-lit rainy night…",
    connection: "Generation route",
    defaultMode: "Site experience",
    customMode: "Bring your own key",
    defaultUnavailable: "Site experience is not enabled yet",
    defaultUnavailableDesc: "Provider, model, and the site relay are all intentionally empty. No legacy fallback will be used.",
    localPreviewReady: "Local demo available",
    localPreviewDesc: "This preview uses deterministic sample copy. It calls no model and sends no network request.",
    noProvider: "No reviewed provider yet",
    provider: "Provider",
    modelId: "Model ID",
    apiKey: "API key",
    clearKey: "Clear now",
    privacy: "This site keeps the key only in the current page's memory. It is not written to browser storage, cookies, logs, or a database, and is discarded on refresh, close, or Clear. Browsers, extensions, and providers may still process it under their own mechanisms; decline password-manager saving and use a limited, revocable key.",
    route: "Network route",
    routeBrowser: "Browser",
    routeEmpty: "No provider selected",
    copyFailed: "Copy failed. Use Download or select the result text manually.",
    selectedSummary: "{count} axes selected; {structure} shape the fate structure",
    semanticRequirement: "Choose at least one axis from circumstance, core, and bond",
    previewResult: "Preview result",
    generate: "Generate",
    cancel: "Cancel",
    resultEyebrow: "This fate thread",
    resultTitle: "The fate has taken shape",
    backToAxes: "Adjust axes and generate again",
    copyAll: "Copy all",
    copied: "Copied",
    download: "Download Markdown",
    outline: "Result outline",
    sourceLocal: "Local demo · no network request",
    sourcePending: "No model connected",
    incomplete: "Three narrative anchors are still missing",
    incompleteDetail: "Choose at least one axis from circumstance, core, and bond, or ask for a starting point.",
    helpTitle: "How to use the fate axes",
    helpIntro: "These axes are not a form to complete. They are narrative variables that can put pressure on one another.",
    helpPointOne: "Begin with three anchors: one circumstance, one core, and one bond.",
    helpPointTwo: "The fate thread shows only encoded rules; it never invents an explanation.",
    helpPointThree: "High-tension combinations are not errors. The system only shows what the story must carry.",
    close: "Close",
    paletteOutside: "Textual palette never enters the causal fate thread.",
  },
} as const;

export type UiCopy = (typeof UI_COPY)[Locale];

export function interpolate(
  template: string,
  values: Readonly<Record<string, string | number>>,
): string {
  return template.replace(/\{([^}]+)\}/g, (_, key: string) =>
    String(values[key] ?? ""),
  );
}
